pin gcloud to old nixpkgs revision as newer one breaks
         > error: auto-patchelf could not satisfy dependency
libtcl9tk9.0.so wanted by

/nix/store/clyhafqxzpafb6p1n6xzniy93b4wkg4z-bundled-python3-unix-linux-x86_64-3.14.5/google-cloud-sdk/platform/bundledpython

unix/lib/python3.14/lib-dynload/_tkinter.cpython-314-x86_64-linux-gnu.so